---
title: "R Notebook"
---
```{r}
install.packages('rvest')
install.packages('RSelenium')
install.packages('dplyr')
install.packages('lubridate')

```

```{r}
library(rvest)
library(RSelenium)
library(dplyr)
library(lubridate)
```

# 先抓一頁試試看
```{r}
html<-read_html("https://www.readr.tw/category/all")
title<-html_text(html_nodes(html,'.title p'))
url<-html_attr(html_nodes(html,'.gzAxbO'),"href")
date<-html_text(html_nodes(html,'.date'))
readtime<-html_text(html_nodes(html,'.read'))

#title<-title[1:12]

data<-data.frame(title=title,url=url,date=date,readtime=readtime)
write.csv(data,"data.csv",row.names = FALSE)
```

# 動態截 html＋靜態解析
先去終端機打：java -jar selenium-server-standalone-3.141.59.jar 

## 設定 selenium
```{r}
remDr <- remoteDriver(
  remoteServerAddr = "localhost",
  port = 4444,
  browserName = "chrome")
```

## 先抓第一頁試試看
```{r}
#動態部分
remDr$open()
remDr$navigate("https://kma.kkbox.com/charts/daily/newrelease?date=2012-08-01&lang=tc&terr=tw#")
result<-remDr$getPageSource()[[1]]

#以下進到靜態
html<-read_html(result)
title<-html_text(html_nodes(html,'.charts-list-song'))
#print(title)
#問 chatgpt:
singer<-html_text(html_nodes(html,'.charts-list-artist'))
singer<-subset(singer, singer != "")
releasedate<-html_text(html_nodes(html,'.charts-list-date'))
releasedate<-subset(releasedate, releasedate != "")
url<-html_attr(html_nodes(html,'.charts-list-song'),"href")

rank<-data.frame(title=title,singer=singer,releasedate=releasedate)
```

## 觀察網址
https://kma.kkbox.com/charts/daily/newrelease?date=2012-08-01&lang=tc&terr=tw#
https://kma.kkbox.com/charts/daily/newrelease?date=2012-08-02&lang=tc&terr=tw#
https://kma.kkbox.com/charts/daily/newrelease?date=2012-08-03&lang=tc&terr=tw#

```{r}
#生成日期清單
date<-ymd("2012-08-01"):ymd("2023-07-26")
date<-as.Date(date,origin="1970-01-01")
date_list<-data.frame(date=date)
date_list$url<-paste0("https://kma.kkbox.com/charts/daily/newrelease?date=",date_list$date,"&lang=tc&terr=tw#")
```

## 寫迴圈
```{r}
for(q in 1:nrow(date_list)){
  
  
}
  
```

# final
```{r}
rank_all<-data.frame()

remDr$open()
for(q in 1:nrow(date_list)){
  print(q)
    remDr$navigate(date_list$url[q])
    Sys.sleep(2)
    result<-remDr$getPageSource()[[1]]
    
    html<-read_html(result)
    title<-html_text(html_nodes(html,'.charts-list-song'))
    title<-subset(title, title != "")
    singer<-html_text(html_nodes(html,'.charts-list-artist'))
    singer<-subset(singer, singer != "")
    releasedate<-html_text(html_nodes(html,'.charts-list-date'))
    releasedate<-subset(releasedate, releasedate != "")
    url<-html_attr(html_nodes(html,'.charts-list-song'),"href")
    date<-date_list$date[q]
    rank<-data.frame(date=date,title=title,singer=singer,releasedate=releasedate)
    rank_all<-rbind(rank_all,rank)
    
    Sys.sleep(1)
}
  
```

#測試
```{r}
rank_all<-data.frame()

remDr$open()
for(q in 1:5){
  print(q)
    remDr$navigate(date_list$url[q])
    Sys.sleep(2)
    result<-remDr$getPageSource()[[1]]
    
    html<-read_html(result)
    title<-html_text(html_nodes(html,'.charts-list-song'))
    title<-subset(title, title != "")
    singer<-html_text(html_nodes(html,'.charts-list-artist'))
    singer<-subset(singer, singer != "")
    releasedate<-html_text(html_nodes(html,'.charts-list-date'))
    releasedate<-subset(releasedate, releasedate != "")
    url<-html_attr(html_nodes(html,'.charts-list-song'),"href")
    date<-date_list$date[q]
    rank<-data.frame(date=date,title=title,singer=singer,releasedate=releasedate)
    rank_all<-rbind(rank_all,rank)
    
    Sys.sleep(1)
}
```
