---
title: "R Notebook"
---

# Selenium

# 啟動 Selenium，先去終端機打
## for macbook
```{r}
java -jar selenium-server-standalone-3.141.59.jar 
```

## for windows（若檔案是放 D 槽）
```{r}
java -Dwebdriver.chrome.driver=D:chromedriver.exe -jar selenium-server-standalone-3.141.59.jar
```

# 以下才是在 R 執行的 code
```{r}
install.packages("RSelenium")
```

```{r}
library(RSelenium)
library(rvest)
```

# 指定機器人為 remDr（若要更改瀏覽器可替換 chrome 為 firefox，但記得下載對應的 driver）
```{r}
remDr <- remoteDriver(
  remoteServerAddr = "localhost",
  port = 4444,
  browserName = "chrome")
```

# 開啟瀏覽器
```{r}
remDr$open()
```

# 連線到指定網址
```{r}
remDr$navigate("https://roadsafety.tw/AccLocCbi")
```
# 關閉瀏覽器
```{r}
remDr$close()
```

# 常用指令
```{r}
# 點選按鈕
enter<-remDr$findElement(using="xpath",'//*[@id="bSearch"]') #先指定位置
enter$clickElement() #點選

# 點選選單（直接找到選項的位置）
year<-remDr$findElement(using="xpath",'//*[@id="ddlCyear"]/option[2]') #先指定位置
year$clickElement() #點選

# 輸入文字
remDr$navigate("https://judgment.judicial.gov.tw/FJUD/default.aspx") #先換到一個有輸入框的網站示範
search<-remDr$findElement(using="xpath",'//*[@id="txtKW"]')  
search$sendKeysToElement(list("違反社會秩序維護法"))
```

# 點選到想要的頁面之後，再把該頁的 html 抓下來，搭配 rvest（讀取靜態網頁）抓取資料
```{r}
webpage<-read_html(remDr$getPageSource()[[1]])

grepl("基隆路四段",webpage) #測試有沒有抓到

table<-html_table(webpage)
table_result<-data.frame(table[[1]])
```

# 搭配迴圈概念，抓 113~106 年 台北市
```{r}
result_all<-data.frame()

remDr$open()
remDr$navigate("https://roadsafety.tw/AccLocCbi")

for(y in 1:8){
  year<-remDr$findElement(using="xpath",paste0('//*[@id="ddlCyear"]/option[',y,']'))
  year$clickElement()
  
  enter<-remDr$findElement(using="xpath",'//*[@id="bSearch"]')
  enter$clickElement()
  Sys.sleep(1.5)

  webpage<-read_html(remDr$getPageSource()[[1]])
  
  check<-grepl("查無資料",webpage)
  table<-html_table(webpage)
  result<-as.data.frame(table[[1]])
  
  result_all<-rbind(result)
  
  #如果你想要再進一步抓裡面的資料
  ncount<-nrow(result)
  
   if(check=="TRUE")
    next
      
        for (i in 1:ncount){
          print(i)
          temp<-remDr$findElement(using="xpath",paste0('//*[@id="tbMain"]/tbody/tr[1]/td[',i,']'))
          temp$clickElement()
          Sys.sleep(1.5)
          webpage<-read_html(remDr$getPageSource()[[1]])
          table<-html_table(webpage)
          table1<-as.data.frame(table[[1]])
          table2<-as.data.frame(table[[2]])
          table3<-as.data.frame(table[[3]])
          table4<-as.data.frame(table[[4]])
          
          #看你想要怎麼存資料，這裡我就沒寫
}
}
```
